### ISSUE TITLE
Thank you for building this :)

### ISSUE THREAD

**Issue by joshbode** [kitagry/bqls#171]
Thank you, @kitagry - I've just started to try out `bqls` and I managed to get it running on Neovim, with completion and error reporting!

![image](https://github.com/user-attachments/assets/57a1c415-079f-4a67-8630-9c15eb44f584)

I know this is a work in progress, but I just wanted to say thank you for putting this together. I'll report any issues I find. If there is anything I can do to help with testing please let me know!

Additionally, I have requested for `bqls` to be added to the Neovim LSP configuration repository: https://github.com/neovim/nvim-lspconfig/pull/3486

It is a very basic configuration currently - I'm not sure what is configurable in `bqls`, but when I learn more I'll add to the configuration, which is hopefully accepted :)

**Comment by joshbode** [comment]
I just noticed https://github.com/kitagry/bqls.nvim (which integrates with `nvim-lspconfig`) - I'll check that out, also

**Comment by kitagry** [comment]
Thank you for the report. I'm waiting for your bug report or contribution :+1:
