### ISSUE TITLE
`QUALIFY` is not supported

### ISSUE THREAD

**Issue by joshbode** [kitagry/bqls#180]
The [`QUALIFY` clause](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#qualify_clause) is not supported, giving the diagnostic error: `INVALID_ARGUMENT: QUALIFY is not supported`

```sql
WITH
  x AS (
    SELECT 1 id, 1 value
    UNION ALL
    SELECT 1 id, 2 value
    UNION ALL
    SELECT 2 id, 3 value
  )
SELECT
  *
FROM
  x
QUALIFY
  COUNT(1) OVER (PARTITION BY id) > 1
```

<img width="727" alt="image" src="https://github.com/user-attachments/assets/15d01ad3-647e-420d-8eab-9f457e305f5e">

**Comment by joshbode** [comment]
Thank you!

**Comment by joshbode** [comment]
@kitagry - I'm still getting the error on version `0.2.1` (I also tried with the latest code on `main`):

```
❱ go install github.com/kitagry/bqls@v0.2.1
...
❱ which bqls
/Users/josh/.local/share/go/bin/bqls
❱ bqls --version
bqls v0.0.0 (rev: /go1.23.3)
```

<img width="714" alt="image" src="https://github.com/user-attachments/assets/cb4b0e5d-4a2e-4647-85bf-aa1b79b371ca">

**Comment by kitagry** [comment]
I think this is related with https://github.com/google/zetasql/issues/124. I'll fix it within a few days.

**Comment by joshbode** [comment]
No worries - thank you!

**Comment by joshbode** [comment]
It works! Thank you @kitagry :)
